# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: iqiyi_sign

on:
  schedule:
    - cron: '0 16 * * *'
  watch:
    types: started
  repository_dispatch:
    types: iqiyi_sign
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/flatpig/signCollection.git ~/scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
      - name: '运行 【爱奇艺签到】'
        run: |
          cd ~/scripts
          node iqiyi.js
        env:
          IQIYI_COOKIE: ${{ secrets.IQIYI_COOKIE }}
